### ISSUE TITLE
Location of Installed Plugins Requested

### ISSUE THREAD

**Issue by cprin21** [solopasha/hyprlandRPM#10]
After installing hyprland-plugins, the way you enable them is by pointing a plugin via its path.
What are the paths for plugins installed via hyprland-plugins with this COPR?

**Comment by solopasha** [comment]
/usr/lib64/hyprland/, for ex:
```
❯ rpm -ql hyprland-plugin-hyprtrails
/usr/lib/.build-id
/usr/lib/.build-id/0c
/usr/lib/.build-id/0c/c36ee769f8119cc3488d5b94e40456f6fafd4a
/usr/lib64/hyprland
/usr/lib64/hyprland/libhyprtrails.so
/usr/share/licenses/hyprland-plugin-hyprtrails
/usr/share/licenses/hyprland-plugin-hyprtrails/LICENSE
```

**Comment by cprin21** [comment]
With hyprland-plugins installed, /usr/lib64/hyprland/ does not exist.

**Comment by solopasha** [comment]
hyprland-plugins is just a meta-package that pulls in all plugins (separate packages) via weak dependencies.
> Also hyprland-plugin-hyprtrails for example wants me to uninstall hyprland-git and install the base hyprland package

Plugins are tied to the version of hyprland they were build against and won't load with any other one. Currently, there're no builds of plugins for hyprland-git.

**Comment by solopasha** [comment]
hyprland-plugins-git is now available for hyprland-git.
https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/build/6639865/
