### ISSUE TITLE
Hyprland generating a config in /var/lib/ instead of using the home config

### ISSUE THREAD

**Issue by Heus-Sueh** [solopasha/hyprlandRPM#12]
I don't know if this bug is because I'm using the immutable version of Fedora or it's a Hyprland bug.
![image](https://github.com/solopasha/hyprlandRPM/assets/98482469/2954043c-f9d4-4937-a01b-7dc81891f9ba)

It's a very bizarre bug that is happening, but it is resolved if I open another instance of hyprland in tty and then it uses the home config
![image](https://github.com/solopasha/hyprlandRPM/assets/98482469/4e66b007-c3f5-445d-9101-43659471d3ab)

the reason I'm using tty is because sddm doesn't want to start at all and I can't solve it

**Comment by solopasha** [comment]
Are you trying to execute hyprland as the sddm compositor via CompositorCommand=? I don't think it's supported in hyprland.

**Comment by solopasha** [comment]
You may want to install sddm-wayland-generic(uses weston for the sddm greeter) or sddm-x11. It's probably possible to create something similar to sddm-wayland-sway (minimal config + wrapper) if you want to use hyprland for the greeter, but I'm not very interested in doing that right now

**Comment by Heus-Sueh** [comment]
> Are you trying to execute hyprland as the sddm compositor via CompositorCommand=? I don't think it's supported in hyprland.

To tell the truth I don't even know what I'm doing lol, I just wanted to create my own distro, but sddm is really annoying to use

**Comment by Heus-Sueh** [comment]
> You may want to install sddm-wayland-generic(uses weston for the sddm greeter) or sddm-x11. It's probably possible to create something similar to sddm-wayland-sway (minimal config + wrapper) if you want to use hyprland for the greeter, but I'm not very interested in doing that right now

something similar to that, right?
https://gitlab.com/fedora/sigs/sway/sway-config-fedora/-/tree/fedora?ref_type=heads

what files would I have to modify to create this wrapper?

**Comment by solopasha** [comment]
I checked your viper repo and was able to get sddm to work with https://github.com/solopasha/viper-test/commit/57d81394e214a1c895ca61df4d1438f9a0a4fead. But when I rebased from silverblue, the sddm user was somehow missing (it was present when I rebased in another VM from your ISO) and sddm refused to start¯\_(ツ)_/¯.  Too fragile and non reproducible, but some people claim otherwise...

> what files would I have to modify to create this wrapper?

Check contents of the sddm-wayland-sway package.

I'll close this as it's not a packaging issue.

**Comment by Heus-Sueh** [comment]
> I checked your viper repo and was able to get sddm to work with [solopasha/viper-test@57d8139](https://github.com/solopasha/viper-test/commit/57d81394e214a1c895ca61df4d1438f9a0a4fead). But when I rebased from silverblue, the sddm user was somehow missing (it was present when I rebased in another VM from your ISO) and sddm refused to start¯_(ツ)_/¯. Too fragile and non reproducible, but some people claim otherwise...
> 
> > what files would I have to modify to create this wrapper?
> 
> Check contents of the sddm-wayland-sway package.
> 
> I'll close this as it's not a packaging issue.

Did hyprland generate another hyprland.conf instead of using the home file or did it work normally?

**Comment by solopasha** [comment]
It worked normally. Your issue is that you use Hyprland in CompositorCommand=. It's NOT autostart, but what to use to "render" sddm and sddm sets /var/lib/sddm as HOME for this process.

**Comment by Heus-Sueh** [comment]
> It worked normally. Your issue is that you use Hyprland in CompositorCommand=. It's NOT autostart, but what to use to "render" sddm and sddm sets /var/lib/sddm as HOME for this process.

thanks for the help man and sorry for bothering you
