### ISSUE TITLE
Thanks for packaging my toy

### ISSUE THREAD

**Issue by cyrinux** [solopasha/hyprlandRPM#14]
Hello, 

Author of https://github.com/hyprland-community/hyprland-autoname-workspaces here, I want to say thanks for packaging it.

I'm considering trying fedora and was thinking if I will need to maintains it myself.

I add a note in the README for fedora users https://github.com/hyprland-community/hyprland-autoname-workspaces/commit/559c14a30e29d37994eb4ccc12280e32c1202845

🍪 🍰

**Comment by solopasha** [comment]
Thanks for your work!
