### ISSUE TITLE
Fedora libdrm 2.4.118.1 vs libdrm 2.4.117.1

### ISSUE THREAD

**Issue by ad-on-is** [solopasha/hyprlandRPM#15]
Hi,

thx. for packaging hyprland and kitt.
Is there  a reason why this repo provides a newer version of libdrm (2.4.118.1) instead of relying on the existing one in the Fedora repos (2.4.117.1)?

I alway get these error messages, and gnome-shell also relies on libdrm, so I'd rather prefer to stick to the official ones.

` - cannot install both libdrm-2.4.118-1.fc39.x86_64 from copr:copr.fedorainfracloud.org:solopasha:hyprland and libdrm-2.4.117-1.fc39.x86_64 from @System`

Cheers.

**Comment by solopasha** [comment]
Newer version of wlroots (bundled with hyprland) requires it. See https://github.com/solopasha/hyprlandRPM/issues/11 for the fix. If you are using an immutable edition of fedora, you probably need something like this: `rpm-ostree override --experimental replace libdrm --from repo=copr:copr.fedorainfracloud.org:solopasha:hyprland`
