### ISSUE TITLE
missing RPM in xdg-desktop-portal-hyprland.spec

### ISSUE THREAD

**Issue by jpeeler** [solopasha/hyprlandRPM#2]
I wasn't able to get screen sharing to work without qt6-qtwayland:

Jun 28 16:16:20 localhost.localdomain hyprland-share-picker[4495]: qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
Jun 28 16:16:20 localhost.localdomain hyprland-share-picker[4495]: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Did you already have this installed on your system?

**Comment by solopasha** [comment]
> Did you already have this installed on your system?

Yes, I also have sway installed which installs qt6-qtwayland as a weak dependency.
