### ISSUE TITLE
Package update request: github.com/Aylur/ags

### ISSUE THREAD

**Issue by mrhyperbit** [solopasha/hyprlandRPM#23]
### Description
I would like to request the update of a package in the Fedora Copr repository. 
(https://github.com/Aylur/ags)

### Package Information

- **Package Name**: [ags]
- **Package Description**: [A customizable and extensible shell]
-  **Package URL**: [Aylur/ags](https://github.com/Aylur/ags)

### Additional Information
[1.8.0](https://github.com/Aylur/ags/releases/tag/v1.8.0)

Creating an ags-git package would be highly beneficial since AGS undergoes continuous development with frequent updates.

**Comment by solopasha** [comment]
It have been failing to build for a while
