### ISSUE TITLE
Dependencies: xorg-x11-server-Xwayland version

### ISSUE THREAD

**Issue by Jaques22** [solopasha/hyprlandRPM#3]
Hi, I'm using your copr repo to install hyprland on ublue and i'm getting a version mismatch for `xorg-x11-server-Xwayland`. 
The spec file was recently changed to require a minimum version of 23.1.2, added in ded2559 a few days ago. However this has only been pushed to rawhide and not yet fedora 38 or 37 (see https://src.fedoraproject.org/rpms/xorg-x11-server-Xwayland). 

Can this version be lowed back to 22.1.9 or is 23.1.2 a required update for Hyprland?  Currently my system cannot update :(

Here is the exact error I'm getting when updating incase I'm completely misunderstanding something here. 

```
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - package hyprland-0.27.0-1.fc38.x86_64 from copr:copr.fedorainfracloud.org:solopasha:hyprland requires xorg-x11-server-Xwayland(x86-64) >= 23.1.2, but none of the providers can be installed
  - package hyprland-0.27.0-2.fc38.x86_64 from copr:copr.fedorainfracloud.org:solopasha:hyprland requires xorg-x11-server-Xwayland(x86-64) >= 23.1.2, but none of the providers can be installed
  - package hyprland-0.27.0-3.fc38.x86_64 from copr:copr.fedorainfracloud.org:solopasha:hyprland requires xorg-x11-server-Xwayland(x86-64) >= 23.1.2, but none of the providers can be installed
  - cannot install both xorg-x11-server-Xwayland-23.1.2-1.fc38.x86_64 from copr:copr.fedorainfracloud.org:solopasha:hyprland and xorg-x11-server-Xwayland-22.1.9-2.fc38.x86_64 from @System
```

**Comment by solopasha** [comment]
>Can this version be lowed back to 22.1.9 or is 23.1.2 a required update for Hyprland?

Yes, 23.1.2 is required in the latest release, see https://github.com/hyprwm/Hyprland/issues/2635

> However this has only been pushed to rawhide and not yet fedora 38 or 37

It's backported in my repo, so it's some sort of an issue with rpm-ostree... 
I'm not familiar with rpm-ostree, maybe https://coreos.github.io/rpm-ostree/ex-replace/ can help. `rpm-ostree override replace xorg-x11-server-Xwayland --experimental --from repo='copr:copr.fedorainfracloud.org:solopasha:hyprland'`

**Comment by Jaques22** [comment]
Ah ignore me, sorry I didn't look at the actual package list on the copr, just the main description page! Thanks for responding so quickly
