### ISSUE TITLE
Waybar-Hyprland segfault when switching workspaces by click (missing patch?)

### ISSUE THREAD

**Issue by trevnels** [solopasha/hyprlandRPM#4]
Today I noticed that clicking a workspace on waybar's `wlr/workspaces` module results in a crash when `"on-click"` is configured to `"activate"`. Looking at Hyprland's docs, it looks like they make the [following substitution](https://wiki.hyprland.org/Useful-Utilities/Status-Bars/#compiling-manually) before compiling to make workspace switching function correctly:
```bash
sed -i -e 's/zext_workspace_handle_v1_activate(workspace_handle_);/const std::string command = "hyprctl dispatch workspace " + name_;\n\tsystem(command.c_str());/g' src/modules/wlr/workspace_manager.cpp
```
Since this change is not being made in the waybar-hyprland rpm spec, I'm guessing this is the reason for the segfault, since Hyprland currently doesn't support `zext_workspace_handle_v1_activate`. Could this patch be added to the spec? 

Also, thanks for maintaining this COPR!

**Comment by solopasha** [comment]
It's supported https://github.com/hyprwm/Hyprland/commit/086f7249514fcbaf10247ee7bd2c5ddad643d898. But doesn't work with empty workspaces... And I discovered it only now, because I don't use persistent_workspaces...

**Comment by trevnels** [comment]
Can confirm that applying the patch resolves the issue. When I get some free time, I may look around upstream to see if there's a way to fix the behavior there - would be nice to not need the patch anymore
