### ISSUE TITLE
Epoch bump results in hyprland-nvidia downgrade to version 1:0.28.0 (from 0.29.0)

### ISSUE THREAD

**Issue by ZaWertun** [solopasha/hyprlandRPM#6]
Is this the expected behavior?
Version 0.28.0 has some bugs that was resolved in new version.

**Comment by ZaWertun** [comment]
Is there some new bugs on nvidia in version 0.29?
Seems I didn't notice. Could you please add link to the issue?

(I'm talking about this commit: https://github.com/solopasha/hyprlandRPM/commit/54156e8422d0343b410ad74b2d980b5d1838a2c1)

**Comment by solopasha** [comment]
https://github.com/hyprwm/Hyprland/issues/3108 https://github.com/hyprwm/Hyprland/issues/3110
and comments in the AUR. But, if those issues aren't present in all configurations then let's update!

**Comment by ZaWertun** [comment]
Maybe it's some Arch-specific bugs.

**Comment by solopasha** [comment]
https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/build/6356885/

**Comment by ZaWertun** [comment]
Thanks!
